### PR TITLE
[Feat] NotePad

### PR DESCRIPTION
**Pull request by xyizko**
# Description

Implementation of storing notes feature as a _Note Pad Function_ with :
1. Persistence of notes across views 
2. Ability to save the notes as a text file

Fixes # (issue)

#14 

## Type of change

1. Bumped semantic versioning 
2. Added a separate component as a `NotePad.svelte`
3. Notepad is a modal since there is absence of any space for another side bar
4. Ability to store notes on disk, done via [`file-saver`](https://www.npmjs.com/package/file-saver)

### Video Demo 

https://github.com/user-attachments/assets/02c5aba3-c0ee-4844-99c7-7c76801d05f7

Demo Env 

```js
                          ./+o+-       codespace@codespaces-289191
                  yyyyy- -yyyyyy+      OS: Ubuntu 20.04 focal
               ://+//////-yyyyyyo      Kernel: x86_64 Linux 6.5.0-1025-azure
           .++ .:/++++++/-.+sss/`      Uptime: 36m
         .:++o:  /++++++++/:--:/-      Packages: 638
        o:+o+:++.`..```.-/oo+++++/     Shell: fish 3.1.0
       .:+o:+o/.          `+sssoo+/    Disk: 54G / 105G (54%)
  .++/+:+oo+o:`             /sssooo.   CPU: AMD EPYC 7763 64-Core @ 2x 3.242GHz
 /+++//+:`oo+o               /::--:.   RAM: 3378MiB / 7929MiB
 \+/+o+++`o++o               ++////.  
  .++.o+++oo+:`             /dddhhh.  
       .+.o+oo:.          `oddhhhh+   
        \+.++o+o``-````.:ohdhhhhh+    
         `:o+++ `ohhhhhhhhyo++os:     
           .o:`.syhhhhhhh/.oo++o`     
               /osyyyyyyo++ooo+++/    
                   ````` +oo+++o\:    
                          `oo++.      
```

- [X] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

Manual Testing

- [X] Test A - Download all files locally and execute docker image. PS: Since im not a webdev i dont know how to write tests for this  type of visual functionality

# Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my code
- [X] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings

### CODE REVIEW

**Comment by eldraco** [comment]
This is so nice! thanks. Let us check it

**Comment by HappyStoic** [comment]
Hey @xyizko, sorry it took us so long to review your PR!

I reviewed the proposal and we can merge it if you are able to make small modifications:

1. Please do not change code not related with the PR. In this case, I mean the addition of `;` on multiple lines. It adds confustion to the git history when contributors are searching for explanation (commit messages) of given lines using `git blame`. 
2. Currently we are not bumping version in dashboard's `package.json` because we are not making any remote releases so we keep it 1.0.0.
3. I don't think the notepad needs a feature to download a file locally to a host machine. Leaving only one button "close" or "save" that stores the current content to the browser's local storage is enough.

Thank you for the contribution!

**Comment by HappyStoic** [comment]
> I tend to use this download feature when i prune the docker images. IMHO this should be part of any notebook functionality ? What is your take on the matter ?

The notes should be persistent. In your implementation, it's persistent in the local storage of a browser. Second option is to mount a persistent directory the the dashboard container and store the notes in this directory in a file. In both ways, the note is persistent even if you remove the container or image.

**Comment by xyizko** [comment]
Thank for the replies and the explanation.  Let me look into how to mount a directory and store the notes as a file , which are written from browser storage.

**Pull request closed without merging**
